### ISSUE TITLE
Crash after exiting sleep

### ISSUE THREAD

**Issue by kettle11** [kettle11/devserver#4]
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /Users/iank/.cargo/registry/src/github.com-1ecc6299db9ec823/devserver_lib-0.1.3/src/lib.rs:96:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C```

Put Macbook to sleep and came back from sleep and devserver had crashed.

**Comment by kettle11** [comment]
Again I hit this: 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /Users/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/devserver_lib-0.1.7/src/lib.rs:100:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /Users/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/devserver_lib-0.1.7/src/lib.rs:100:49
```
